#!/bin/sh
set -eu
cp -R /input/. /workspace/
cd /workspace
files=$(find .strix-tests -type f \( -name '*.test.js' -o -name '*.test.mjs' -o -name '*.test.cjs' -o -name '*.test.ts' \))
if [ -z "$files" ]; then
  echo '{"results":[]}'
  exit 1
fi
# Paths are generated by Strix and do not contain spaces.
# shellcheck disable=SC2086
exec node --experimental-strip-types --test --test-reporter /opt/strix/reporter.cjs $files
